### ISSUE TITLE
Should use DIRECTORY_SEPARATOR in the first 2 "require_once"

### ISSUE THREAD

**Issue by assaneonline** [deltastateonline/ml-php#1]
Here :
https://github.com/deltastateonline/ml-php/blob/50d645ba003caa5ae386cefdf74d3335869291fd/image.creation.php#L6
https://github.com/deltastateonline/ml-php/blob/50d645ba003caa5ae386cefdf74d3335869291fd/image.creation.php#L7

**Comment by deltastateonline** [comment]
thanks, I normally use it 
`define('DS',DIRECTORY_SEPARATOR);`
but in this case I forgot
