### ISSUE TITLE
hog feature

### ISSUE THREAD

**Issue by ghostjat** [deltastateonline/ml-php#2]
hey @deltastateonline 
i want to implement hog feature based object detection.
i am able to pull descriptor blocks from image but i am confusing with labeling as well as it is a huge feature vector from single image.
would you please guide me how to implement this in php

**Comment by deltastateonline** [comment]
Hi,
I really have no idea on how to achieve what you are trying to do.
But my advise will be to use the right tool for the job ie use python, which has a lot of libraries built for ML and computer vision.

Good luck
